language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - DISPLAY=:99.0
    - BROWSER_NAME="htmlunit"
    - SELENIUM_MAJOR_VERSION="3.8"
    - SELENIUM_MINOR_VERSION="1"
    - GECKODRIVER_VERSION="v0.24.0"

matrix:
  include:
    # Add build to run tests against Firefox with Geckodriver (W3C mode) inside Travis environment
    - php: 7.3
      env:
        - BROWSER_NAME="firefox"
        - GECKODRIVER="1"
      addons:
        firefox: "latest"

    # Add build to run tests against Firefox inside Travis environment
    - php: 7.3
      env: BROWSER_NAME="firefox"
      addons:
        firefox: "45.8.0esr"

    # Add build to run tests against Chrome inside Travis environment
    - php: 7.3
      env: BROWSER_NAME="chrome" HEADLESS="1"
      addons:
        chrome: stable

    # Build with lowest possible dependencies
    - php: 7.3
      env: DEPENDENCIES="--prefer-lowest"

    # Chrome on Travis build with lowest possible dependencies
    - php: 7.3
      env: BROWSER_NAME="chrome" HEADLESS="1" DEPENDENCIES="--prefer-lowest"
      addons:
        chrome: stable

    # Saucelabs builds
    - php: 7.3
      env: SAUCELABS=1 BROWSER_NAME="firefox" VERSION="47.0" PLATFORM="Windows 10"
      before_script:
        - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
        - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"
      addons:
        sauce_connect: true
        jwt:
          secure: "UfAIRBKp5GET94LJSnJmF0VmdRbfXx4JsWKsQYwwGnXYaFUj2vxThg7VA+GrnbvX1amiUqz2mXHLvMxsJZrukT86RSjQJHXeEX17aZ2dp4LP1aPbSUkIxjygNFjiF/7kOC4W7EGNO/fFUnXD9RFmqiWdNh/BY9vh1JCtV9sO04npYQJPwywjOGani7mUtf0yJQETWtul1QN6fSOZKn1Pmrhtfkayn6CP3sjNotjApSImlqNI2hIEigqSyOzXeZHuHeqa14LoCM9JUUC4o3LMcdkita9D6q7krUwsvVL7JwFVvsYQEp9Mtcx/yNxAsed0XjhXR7PLpUuvGqt+n8DkmYehG1Z7pXtEhaHHEvY56xIMtI9Vw5dX1WA7Y4vKrbZeewi/l1HvNVxGpF9GdEeHgr4f2aId6BWhAXyXsmdfwfxKlj/WUnFC/zs7ThJcnDACSbcs0ASlJXhCs8coJ4/skA20XGrgdUzIqJ4X1iLHtih3iXA4lFfFQXSYIptE3yZ4mQ8Pb+yzcs3uCRBXZkDvYvaqfjhKWR9EblO7A5uT+7K24zhu3Kove14YOKSZnuesmD1V3qnWMKQIMJ5JkvqJB9YlcqWZXh8znfFNg+dLx7dGpkpdeJ6lidS5PPEx1bnIkjOTkUjGy45NsQEtfwt/Yd1B/xa9xVHdT3AEOd77ASI="
    - php: 7.3
      env: SAUCELABS=1 BROWSER_NAME="chrome" VERSION="latest" PLATFORM="Windows 10"
      before_script:
        - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
        - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"
      addons:
        sauce_connect: true
        jwt:
          secure: "UfAIRBKp5GET94LJSnJmF0VmdRbfXx4JsWKsQYwwGnXYaFUj2vxThg7VA+GrnbvX1amiUqz2mXHLvMxsJZrukT86RSjQJHXeEX17aZ2dp4LP1aPbSUkIxjygNFjiF/7kOC4W7EGNO/fFUnXD9RFmqiWdNh/BY9vh1JCtV9sO04npYQJPwywjOGani7mUtf0yJQETWtul1QN6fSOZKn1Pmrhtfkayn6CP3sjNotjApSImlqNI2hIEigqSyOzXeZHuHeqa14LoCM9JUUC4o3LMcdkita9D6q7krUwsvVL7JwFVvsYQEp9Mtcx/yNxAsed0XjhXR7PLpUuvGqt+n8DkmYehG1Z7pXtEhaHHEvY56xIMtI9Vw5dX1WA7Y4vKrbZeewi/l1HvNVxGpF9GdEeHgr4f2aId6BWhAXyXsmdfwfxKlj/WUnFC/zs7ThJcnDACSbcs0ASlJXhCs8coJ4/skA20XGrgdUzIqJ4X1iLHtih3iXA4lFfFQXSYIptE3yZ4mQ8Pb+yzcs3uCRBXZkDvYvaqfjhKWR9EblO7A5uT+7K24zhu3Kove14YOKSZnuesmD1V3qnWMKQIMJ5JkvqJB9YlcqWZXh8znfFNg+dLx7dGpkpdeJ6lidS5PPEx1bnIkjOTkUjGy45NsQEtfwt/Yd1B/xa9xVHdT3AEOd77ASI="
    - php: 7.3
      env: SAUCELABS=1 BROWSER_NAME="MicrosoftEdge" VERSION="15.15063" PLATFORM="Windows 10"
      before_script:
        - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
        - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"
      addons:
        sauce_connect: true
        jwt:
          secure: "UfAIRBKp5GET94LJSnJmF0VmdRbfXx4JsWKsQYwwGnXYaFUj2vxThg7VA+GrnbvX1amiUqz2mXHLvMxsJZrukT86RSjQJHXeEX17aZ2dp4LP1aPbSUkIxjygNFjiF/7kOC4W7EGNO/fFUnXD9RFmqiWdNh/BY9vh1JCtV9sO04npYQJPwywjOGani7mUtf0yJQETWtul1QN6fSOZKn1Pmrhtfkayn6CP3sjNotjApSImlqNI2hIEigqSyOzXeZHuHeqa14LoCM9JUUC4o3LMcdkita9D6q7krUwsvVL7JwFVvsYQEp9Mtcx/yNxAsed0XjhXR7PLpUuvGqt+n8DkmYehG1Z7pXtEhaHHEvY56xIMtI9Vw5dX1WA7Y4vKrbZeewi/l1HvNVxGpF9GdEeHgr4f2aId6BWhAXyXsmdfwfxKlj/WUnFC/zs7ThJcnDACSbcs0ASlJXhCs8coJ4/skA20XGrgdUzIqJ4X1iLHtih3iXA4lFfFQXSYIptE3yZ4mQ8Pb+yzcs3uCRBXZkDvYvaqfjhKWR9EblO7A5uT+7K24zhu3Kove14YOKSZnuesmD1V3qnWMKQIMJ5JkvqJB9YlcqWZXh8znfFNg+dLx7dGpkpdeJ6lidS5PPEx1bnIkjOTkUjGy45NsQEtfwt/Yd1B/xa9xVHdT3AEOd77ASI="

    # Codestyle check build
    - php: 7.3
      env: CHECK_CODESTYLE=1
      before_install:
        - phpenv config-rm xdebug.ini
      before_script: ~
      script:
        - composer require phpstan/phpstan-shim # Not part of require-dev, because it won't install on PHP 5.6
        - composer analyze
        - composer codestyle:check
      after_script: ~
      after_success: ~

cache:
  directories:
    - $HOME/.composer/cache
    - jar

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction $DEPENDENCIES

before_script:
  - |
    if [ "$BROWSER_NAME" = "chrome" ]
    then
      mkdir chromedriver
      CHROME_VERSION=`google-chrome-stable --version | awk '{print $NF}' | sed 's/\.[0-9]*$//'`
      echo "Chrome version is $CHROME_VERSION"
      CHROMEDRIVER_VERSION=`curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION`
      echo "chromedriver version is $CHROMEDRIVER_VERSION"
      wget -q -t 3 https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
      unzip chromedriver_linux64 -d chromedriver
    fi
  - if [ "$BROWSER_NAME" = "chrome" ]; then export CHROMEDRIVER_PATH=$PWD/chromedriver/chromedriver; fi
  - |
    mkdir geckodriver
    wget -q -t 3 https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
    tar xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
    export PATH="$PATH:`pwd`/geckodriver"
  - sh -e /etc/init.d/xvfb start
  - if [ ! -f jar/selenium-server-standalone-$SELENIUM_MAJOR_VERSION.$SELENIUM_MINOR_VERSION.jar ]; then wget -q -t 3 -P jar https://selenium-release.storage.googleapis.com/$SELENIUM_MAJOR_VERSION/selenium-server-standalone-$SELENIUM_MAJOR_VERSION.$SELENIUM_MINOR_VERSION.jar; fi
  - |
    if [ "$GECKODRIVER" = "1" ]
    then
      geckodriver/geckodriver &> ./logs/geckodriver.log &
    else
      java -Dwebdriver.chrome.driver="$CHROMEDRIVER_PATH" -jar jar/selenium-server-standalone-$SELENIUM_MAJOR_VERSION.$SELENIUM_MINOR_VERSION.jar -log ./logs/selenium.log &
    fi
  - until $(echo | nc localhost 4444); do sleep 1; echo Waiting for Selenium server on port 4444...; done; echo "Selenium server started"
  - php -S 127.0.0.1:8000 -t tests/functional/web/ &>>./logs/php-server.log &
  - until $(echo | nc localhost 8000); do sleep 1; echo waiting for PHP server on port 8000...; done; echo "PHP server started"

script:
  - if [ -n "$SAUCELABS" ]; then EXCLUDE_GROUP+="exclude-saucelabs,"; fi
  - if [ "$BROWSER_NAME" = "MicrosoftEdge" ]; then EXCLUDE_GROUP+="exclude-edge,"; fi
  - if [ -n "$EXCLUDE_GROUP" ]; then EXTRA_PARAMS+=" --exclude-group $EXCLUDE_GROUP"; fi
  - ./vendor/bin/phpunit --coverage-clover ./logs/coverage-clover.xml $EXTRA_PARAMS

after_script:
  - if [ -f ./logs/selenium.log ]; then cat ./logs/selenium.log; fi
  - if [ -f ./logs/php-server.log ]; then cat ./logs/php-server.log; fi

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
